config/routes.rb
Rails.application.routes.draw do
  resources :problemas
  resources :evaluacions
  resources :users
  get 'welcome/index'

  root 'welcome#index'

end

app/models/evaluacion.rb
class Evaluacion < ActiveRecord::Base
  has_many :problemas
end

app/models/problema.rb
class Problema < ActiveRecord::Base
  belongs_to :evaluacion
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/evaluacions_controller.rb
class EvaluacionsController < ApplicationController
  before_action :set_evaluacion, only: [:show, :edit, :update, :destroy]

  # GET /evaluacions
  # GET /evaluacions.json
  def index
    @evaluacions = Evaluacion.all
  end

  # GET /evaluacions/1
  # GET /evaluacions/1.json
  def show
  end

  # GET /evaluacions/new
  def new
    @evaluacion = Evaluacion.new
  end

  # GET /evaluacions/1/edit
  def edit
  end

  # POST /evaluacions
  # POST /evaluacions.json
  def create
    @evaluacion = Evaluacion.new(evaluacion_params)

    respond_to do |format|
      if @evaluacion.save
        format.html { redirect_to @evaluacion, notice: 'Evaluacion was successfully created.' }
        format.json { render :show, status: :created, location: @evaluacion }
      else
        format.html { render :new }
        format.json { render json: @evaluacion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /evaluacions/1
  # PATCH/PUT /evaluacions/1.json
  def update
    respond_to do |format|
      if @evaluacion.update(evaluacion_params)
        format.html { redirect_to @evaluacion, notice: 'Evaluacion was successfully updated.' }
        format.json { render :show, status: :ok, location: @evaluacion }
      else
        format.html { render :edit }
        format.json { render json: @evaluacion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /evaluacions/1
  # DELETE /evaluacions/1.json
  def destroy
    @evaluacion.destroy
    respond_to do |format|
      format.html { redirect_to evaluacions_url, notice: 'Evaluacion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_evaluacion
      @evaluacion = Evaluacion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def evaluacion_params
      params.require(:evaluacion).permit(:nombre, :tipo)
    end
end

app/controllers/problemas_controller.rb
class ProblemasController < ApplicationController
  before_action :set_problema, only: [:show, :edit, :update, :destroy]

  # GET /problemas
  # GET /problemas.json
  def index
    @problemas = Problema.all
  end

  # GET /problemas/1
  # GET /problemas/1.json
  def show
  end

  # GET /problemas/new
  def new
    @problema = Problema.new
  end

  # GET /problemas/1/edit
  def edit
  end

  # POST /problemas
  # POST /problemas.json
  def create
    @problema = Problema.new(problema_params)

    respond_to do |format|
      if @problema.save
        format.html { redirect_to @problema, notice: 'Problema was successfully created.' }
        format.json { render :show, status: :created, location: @problema }
      else
        format.html { render :new }
        format.json { render json: @problema.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /problemas/1
  # PATCH/PUT /problemas/1.json
  def update
    respond_to do |format|
      if @problema.update(problema_params)
        format.html { redirect_to @problema, notice: 'Problema was successfully updated.' }
        format.json { render :show, status: :ok, location: @problema }
      else
        format.html { render :edit }
        format.json { render json: @problema.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /problemas/1
  # DELETE /problemas/1.json
  def destroy
    @problema.destroy
    respond_to do |format|
      format.html { redirect_to problemas_url, notice: 'Problema was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_problema
      @problema = Problema.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def problema_params
      params.require(:problema).permit(:nombre, :content, :evaluacion_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/evaluacions_helper.rb
module EvaluacionsHelper
end

app/helpers/problemas_helper.rb
module ProblemasHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/evaluacions/_form.html.erb
<%= form_for(@evaluacion) do |f| %>
  <% if @evaluacion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@evaluacion.errors.count, "error") %> prohibited this evaluacion from being saved:</h2>

      <ul>
      <% @evaluacion.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :tipo %><br>
    <%= f.text_field :tipo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/evaluacions/edit.html.erb
<h1>Editing Evaluacion</h1>

<%= render 'form' %>

<%= link_to 'Show', @evaluacion %> |
<%= link_to 'Back', evaluacions_path %>

app/views/evaluacions/index.html.erb
<div class="container app-header">
<p id="notice"><%= notice %></p>

<h1>Listado de Evaluaciones</h1>

<table clasS="table table-striped">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Tipo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @evaluacions.each do |evaluacion| %>
      <tr>
        <td><%= evaluacion.nombre %></td>
        <td><%= evaluacion.tipo %></td>
        <td><%= link_to 'Show', evaluacion %></td>
        <td><%= link_to 'Edit', edit_evaluacion_path(evaluacion) %></td>
        <td><%= link_to 'Destroy', evaluacion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Evaluacion', new_evaluacion_path, class: "btn btn-primary" %>
</div>

app/views/evaluacions/new.html.erb
<div class="container app-header">
<h1>Crear nueva evaluacion</h1>

<%= render 'form' %>

<%= link_to 'Back', evaluacions_path %>
</div>

app/views/evaluacions/show.html.erb
<div class="container app-header">
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Nombre:</strong>
    <%= @evaluacion.nombre %>
  </p>

  <p>
    <strong>Tipo:</strong>
    <%= @evaluacion.tipo %>
  </p>

  <%= link_to 'Edit', edit_evaluacion_path(@evaluacion) %> |
  <%= link_to 'Back', evaluacions_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Material Design for Bootstrap</title>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <!--Navigation-->
   <nav class="navbar navbar-fixed-top z-depth-1 pt-color" role="navigation">
       <div class="container">
           <div class="navbar-header">
               <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                   <span class="sr-only">Toggle navigation</span>
                   <span class="icon-bar"></span>
                   <span class="icon-bar"></span>
                   <span class="icon-bar"></span>
               </button>

           </div>
           <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
               <ul class="nav navbar-nav">
                   <li><a href="#sec-home" class="waves-effect waves-light">Home <i class="fa fa-home left"></i></a></li>
                   <li><a href="#sec-best-features" class="waves-effect waves-light">Acerca de</a></li>
                   <li><a href="#sec-contact" class="waves-effect waves-light">Contacto</a></li>
                   <li><a href="" class="waves-effect waves-light">Login</a></li>
               </ul>
           </div>
       </div>
   </nav>
   <!--/.Navigation-->


   <%= yield %>

   <!--Section: Footer-->
     <footer class="page-footer pt-color" id="sec-footer">

         <!--Footer Content-->
         <div class="container-fluid footer-content">

             <div class="row text-center wow fadeIn">

                 <h4 class="white-text wow fadeIn">Encuentranos en las Redes sociales</h4>

                 <button type="button" class="btn btn-primary btn-xlg facebook-color waves-effect waves-light fadeInUp"><i class="fa fa-facebook"> </i> <span> Facebook</span> </button>

                 <button type="button" class="btn btn-primary btn-xlg twitter-color waves-effect waves-light fadeInUp" data-wow-delay="0.1s"><i class="fa fa-twitter"> </i> <span> Twitter</span></button>

                 <button type="button" class="btn btn-primary btn-xlg gplus-color waves-effect waves-light fadeInUp" data-wow-delay="0.2s"><i class="fa fa-google-plus"> </i> <span> Google +</span></button>

                 <button type="button" class="btn btn-primary btn-xlg linkedin-color waves-effect waves-light fadeInUp" data-wow-delay="0.3s"><i class="fa fa-linkedin"> </i> <span>LinkedIn</span></button>

                 <button type="button" class="btn btn-primary btn-xlg youtube-color waves-effect waves-light fadeInUp" data-wow-delay="0.6s"><i class="fa fa-youtube"> </i> <span>Youtube</span></button>

             </div>

         </div>
         <!--/.Footer Content-->

          <!--Coprytights-->
         <div class="footer-copyright text-center rgba-black-light wow fadeIn">
             <div class="container-fluid">
                 © 2016 Copyright: <a href="http://www.realitat.com.mx"> Realität </a>
             </div>
         </div>
         <!--/.Coprytights-->

     </footer>
     <!--/.Section: Footer-->


</body>
</html>

app/views/problemas/_form.html.erb
<%= form_for(@problema) do |f| %>
  <% if @problema.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@problema.errors.count, "error") %> prohibited this problema from being saved:</h2>

      <ul>
      <% @problema.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :evaluacion_id %><br>
    <%= f.number_field :evaluacion_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/problemas/edit.html.erb
<h1>Editing Problema</h1>

<%= render 'form' %>

<%= link_to 'Show', @problema %> |
<%= link_to 'Back', problemas_path %>

app/views/problemas/index.html.erb
<div class="container app-header">
<p id="notice"><%= notice %></p>

<h1>Listado de Problemas creados</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Evaluacion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @problemas.each do |problema| %>
      <tr>
        <td><%= problema.nombre %></td>
        <td><%= problema.evaluacion_id %></td>
        <td><%= link_to 'Show', problema %></td>
        <td><%= link_to 'Edit', edit_problema_path(problema) %></td>
        <td><%= link_to 'Destroy', problema, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Problema', new_problema_path, class: "btn btn-primary" %>
</div>

app/views/problemas/new.html.erb
<div class="container app-header">
<h1>Nuevo problema</h1>

<%= render 'form' %>

<%= link_to 'Back', problemas_path %>
</div>

app/views/problemas/show.html.erb
<div class="container app-header">
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @problema.nombre %>
</p>

<p>
  <strong>Content:</strong>
  <%= @problema.content %>
</p>

<p>
  <strong>Evaluacion:</strong>
  <%= @problema.evaluacion_id %>
</p>

<%= link_to 'Edit', edit_problema_path(@problema) %> |
<%= link_to 'Back', problemas_path %>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="container app-header">
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

</div>

app/views/users/index.html.erb
<div class="container app-header">
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>
</div>

app/views/users/new.html.erb
<div class="container app-header">
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>
</div>

app/views/users/show.html.erb
<div class="container app-header">
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>
</div>

app/views/welcome/index.html.erb
<!-- Intro image -->
    <section class="full-bg-img" id="sec-home">
      <!--Mask-->
        <div class="view rgba-black-strong">
          <!--Alignment-->
           <div class="verticalcenter">
               <div class="container">
                   <div class="row">

                     <!--Content-->
                      <div class="col-md-6 white-text wow fadeInLeft">

                        <h2>Evaluación de capital humano</h2>

                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. At ea, eligendi libero quos, alias maxime aperiam iusto tempora quibusdam perspiciatis fugit pariatur vero. Harum enim distinctio quidem ab laudantium sequi.</p>

                        <a href="#sec-best-features" class="btn btn-primary btn-ptc btn-lg waves-effect waves-light">Learn more</a>

                      </div>
                      <!--/.Content-->

                      <!--Form-->
                       <div class="col-md-6 wow fadeInRight">
                           <div class="card-panel">
                             <!--Header-->
                                <div class="text-center">
                                    <h4><i class="fa fa-newspaper-o"></i> Boletín</h4>
                                    <span>Mantente informado</span>
                                </div>
                                <!--/.Header-->
                                <!--Form-->
                                <form>
                                    <div class="input-field">
                                        <i class="material-icons prefix">email</i>
                                        <input id="icon_email" type="tel" class="validate">
                                        <label for="icon_email">Tu email</label>
                                    </div>

                                    <div class="text-center">
                                        <button type="button" class="btn btn-primary btn-lg btn-ptc waves-effect waves-light">Suscribirse</button>
                                    </div>

                                </form>
                                <!--/.Form-->
                           </div>
                       </div>
                       <!--/.Form-->

                   </div>
               </div>
           </div>
           <!--/.Alignment-->
        </div>
        <!--/.Mask-->
    </section>
    <!--/. Intro image -->

    <!--Main container-->
    <div class="container">

      <!--Section: Best Features-->
      <section id="sec-best-features">
          <div class="divider-new">Diferenciadores</div>

          <div class="row">

              <!--First columnn-->
              <div class="col-md-3">
                  <!--Image Card-->
                  <div class="card hoverable">
                      <div class="card-image">
                          <div class="view overlay hm-white-slight z-depth-1">
                              <img src="http://mdbootstrap.com/images/reg/reg%20(2).jpg" class="img-responsive" alt="">
                              <a href="#">
                                  <div class="mask waves-effect"></div>
                              </a>
                          </div>
                      </div>
                      <div class="card-content">
                          <h5>Evaluación Online</h5>
                          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Id amet, quisquam modi.</p>
                      </div>
                  </div>
                  <!--Image Card-->
              </div>
              <!--/.First columnn-->

              <!--Second columnn-->
              <div class="col-md-3">
                  <!--Image Card-->
                  <div class="card hoverable">
                      <div class="card-image">
                          <div class="view overlay hm-white-slight z-depth-1">
                              <img src="http://mdbootstrap.com/images/reg/reg%20(2).jpg" class="img-responsive" alt="">
                              <a href="#">
                                  <div class="mask waves-effect"></div>
                              </a>
                          </div>
                      </div>
                      <div class="card-content">
                          <h5>Consultores Reales</h5>
                          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Id amet, quisquam modi.</p>
                      </div>
                  </div>
                  <!--Image Card-->
              </div>
              <!--/.Second columnn-->

              <!--Third columnn-->
              <div class="col-md-3">
                  <!--Image Card-->
                  <div class="card hoverable">
                      <div class="card-image">
                          <div class="view overlay hm-white-slight z-depth-1">
                              <img src="http://mdbootstrap.com/images/reg/reg%20(2).jpg" class="img-responsive" alt="">
                              <a href="#">
                                  <div class="mask waves-effect"></div>
                              </a>
                          </div>
                      </div>
                      <div class="card-content">
                          <h5>Alto nivel</h5>
                          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Id amet, quisquam modi.</p>
                      </div>
                  </div>
                  <!--Image Card-->
              </div>
              <!--/.Third columnn-->
              <!--Fourth columnn-->
              <div class="col-md-3">
                  <!--Image Card-->
                  <div class="card hoverable">
                      <div class="card-image">
                          <div class="view overlay hm-white-slight z-depth-1">
                              <img src="http://mdbootstrap.com/images/reg/reg%20(2).jpg" class="img-responsive" alt="">
                              <a href="#">
                                  <div class="mask waves-effect"></div>
                              </a>
                          </div>
                      </div>
                      <div class="card-content">
                          <h5>Respuesta en línea</h5>
                          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Id amet, quisquam modi.</p>
                      </div>
                  </div>
                  <!--Image Card-->
              </div>
              <!--/.Fourth columnn-->
          </div>
      </section>
      <!--/.Section: Best Features-->

        <!--Section: Contact-->
          <div class="divider-new">Contactanos</div>
          <section id="sec-contact">

              <!--Contact Form-->
              <!-- Main forms row -->
              <div class="row wow fadeIn">
                  <div class="col-md-8">
                      <div id="map-container" class="card-panel hoverable wow fadeInUp" style="height: 300px"></div>
                  </div>
                  <!-- Contact details -->
                  <div class="col-md-4 text-center">


                      <ul class="contact-data">
                          <li class="wow fadeInUp" data-wow-delay="0.2s"><a class="btn-floating btn-small waves-effect waves-light blue-grey"><i class="material-icons">pin_drop</i></a>
                              <p>México</p>
                          </li>

                          <li class="wow fadeInUp" data-wow-delay="0.3s"><a class="btn-floating btn-small waves-effect waves-light blue-grey" data-toggle="modal" data-target="#contact-form"><i class="material-icons">phone</i></a>
                              <p>+ 01 234 567 89</p>
                          </li>

                          <li class="wow fadeInUp" data-wow-delay="0.4s"><a class="btn-floating btn-small waves-effect waves-light blue-grey" data-toggle="modal" data-target="#contact-form"><i class="material-icons">email</i></a>
                              <p>contacto@evaluaciones.com</p>
                          </li>
                      </ul>
                  </div>
              </div>
              <!--/. Main row -->
          </section>
          <!--Section: Contact-->
    </div>
    <!--/.Main container-->

    <!--Google Maps-->
    <script src="http://maps.google.com/maps/api/js?sensor=false"></script>
    <script>
        function init_map() {
            var var_location = new google.maps.LatLng(19.5418345,-99.2139896);

            var var_mapoptions = {
                center: var_location,
                zoom: 14
            };

            var var_marker = new google.maps.Marker({
                position: var_location,
                map: var_map,
                title: "Evaluaciones"
            });

            var var_map = new google.maps.Map(document.getElementById("map-container"),
                var_mapoptions);

            var_marker.setMap(var_map);
        }

        google.maps.event.addDomListener(window, 'load', init_map);
    </script>